import { Injectable } from "@angular/core";
import { delay, of } from "rxjs";

const STUDENTS = [{
  "id": 1,
  "surName": "Pena",
  "firstName": "Noel",
  "middleName": "Shaffer",
  "lastName": "Dee",
  "gender": "female",
  "parentName": "Knight",
  "phone": "+91 (982) 491-3297",
  "address": "164 Troutman Street, Eureka, American Samoa, 6490",
  "city": "Salunga",
  "state": "Maine",
  "zip": "54365",
  "dateOfBirth": "2014-01-10",
  "class": 1,
  "section": 1
}, {
  "id": 2,
  "surName": "Cardenas",
  "firstName": "Lavonne",
  "middleName": "Roberta",
  "lastName": "Candace",
  "gender": "female",
  "parentName": "Vivian",
  "phone": "+91 (841) 442-3719",
  "address": "346 Jackson Court, Clara, New Jersey, 3689",
  "city": "Drytown",
  "state": "Nevada",
  "zip": 54365,
  "dateOfBirth": "2019-05-28",
  "class": 1,
  "section": 2
}, {
  "id": 3,
  "surName": "Santiago",
  "firstName": "Simpson",
  "middleName": "Loraine",
  "lastName": "Olive",
  "gender": "female",
  "parentName": "Hull",
  "phone": "+91 (811) 412-3418",
  "address": "573 Columbia Street, Bridgetown, North Carolina, 4163",
  "city": "Williams",
  "state": "Washington",
  "zip": 54365,
  "dateOfBirth": "2014-07-21",
  "class": 1,
  "section": 3
}, {
  "id": 4,
  "surName": "Mcdowell",
  "firstName": "Sharp",
  "middleName": "Cannon",
  "lastName": "Lancaster",
  "gender": "male",
  "parentName": "Katy",
  "phone": "+91 (884) 418-3462",
  "address": "413 Pooles Lane, Coaldale, Indiana, 9287",
  "city": "Linwood",
  "state": "Mississippi",
  "zip": 54365,
  "dateOfBirth": "2014-12-03",
  "class": 1,
  "section": 4
}, {
  "id": 5,
  "surName": "Talley",
  "firstName": "Bernice",
  "middleName": "Karen",
  "lastName": "Lawrence",
  "gender": "male",
  "parentName": "Mills",
  "phone": "+91 (866) 592-3966",
  "address": "280 Seigel Court, Grimsley, Wisconsin, 2905",
  "city": "Dola",
  "state": "Texas",
  "zip": 54365,
  "dateOfBirth": "2021-06-12",
  "class": 2,
  "section": 1
}, {
  "id": 6,
  "surName": "Peters",
  "firstName": "Sullivan",
  "middleName": "Christy",
  "lastName": "Mcdonald",
  "gender": "male",
  "parentName": "Ashley",
  "phone": "+91 (824) 600-3641",
  "address": "698 Bedell Lane, Fairlee, Guam, 6725",
  "city": "Robbins",
  "state": "Kentucky",
  "zip": 54365,
  "dateOfBirth": "2014-03-26",
  "class": 2,
  "section": 2
}, {
  "id": 7,
  "surName": "Murray",
  "firstName": "Aileen",
  "middleName": "Jackie",
  "lastName": "Hendrix",
  "gender": "male",
  "parentName": "Tillman",
  "phone": "+91 (942) 544-3461",
  "address": "364 Dahill Road, Sunnyside, Michigan, 5373",
  "city": "Chesapeake",
  "state": "Maryland",
  "zip": 54365,
  "dateOfBirth": "2019-07-23",
  "class": 2,
  "section": 3
}, {
  "id": 8,
  "surName": "Rowland",
  "firstName": "Ilene",
  "middleName": "Michele",
  "lastName": "Gallagher",
  "gender": "male",
  "parentName": "Olson",
  "phone": "+91 (995) 573-3327",
  "address": "989 Hoyts Lane, Greenbush, District Of Columbia, 4480",
  "city": "Chase",
  "state": "Rhode Island",
  "zip": 54365,
  "dateOfBirth": "2019-10-05",
  "class": 2,
  "section": 4
}, {
  "id": 9,
  "surName": "Preston",
  "firstName": "Jillian",
  "middleName": "Meadows",
  "lastName": "Catherine",
  "gender": "female",
  "parentName": "Diann",
  "phone": "+91 (843) 503-2631",
  "address": "293 Holly Street, Mapletown, Wyoming, 558",
  "city": "Adamstown",
  "state": "Georgia",
  "zip": 54365,
  "dateOfBirth": "2018-07-03",
  "class": 3,
  "section": 1
}, {
  "id": 10,
  "surName": "Carlson",
  "firstName": "Josefa",
  "middleName": "Melanie",
  "lastName": "Alford",
  "gender": "male",
  "parentName": "Sonya",
  "phone": "+91 (932) 595-3393",
  "address": "703 Middagh Street, Roland, West Virginia, 2034",
  "city": "Bethpage",
  "state": "Massachusetts",
  "zip": 54365,
  "dateOfBirth": "2017-12-23",
  "class": 3,
  "section": 2
}, {
  "id": 11,
  "surName": "Livingston",
  "firstName": "Patty",
  "middleName": "Larson",
  "lastName": "Leon",
  "gender": "male",
  "parentName": "Gracie",
  "phone": "+91 (898) 442-2459",
  "address": "378 Erskine Loop, Thermal, Vermont, 4098",
  "city": "Bynum",
  "state": "Nebraska",
  "zip": 54365,
  "dateOfBirth": "2017-04-11",
  "class": 3,
  "section": 3
}, {
  "id": 12,
  "surName": "Dickson",
  "firstName": "Esther",
  "middleName": "Bright",
  "lastName": "Mosley",
  "gender": "male",
  "parentName": "Iva",
  "phone": "+91 (829) 470-2744",
  "address": "839 Division Place, Lewis, Tennessee, 4630",
  "city": "Gilgo",
  "state": "Alaska",
  "zip": 54365,
  "dateOfBirth": "2019-07-22",
  "class": 3,
  "section": 4
}, {
  "id": 13,
  "surName": "Rutledge",
  "firstName": "Adeline",
  "middleName": "Aisha",
  "lastName": "Conley",
  "gender": "male",
  "parentName": "Lena",
  "phone": "+91 (932) 402-2607",
  "address": "547 Box Street, Rosine, Utah, 714",
  "city": "Topaz",
  "state": "New Mexico",
  "zip": 54365,
  "dateOfBirth": "2015-10-17",
  "class": 4,
  "section": 1
}, {
  "id": 14,
  "surName": "Erickson",
  "firstName": "Vasquez",
  "middleName": "Kelly",
  "lastName": "Mclaughlin",
  "gender": "male",
  "parentName": "Brandie",
  "phone": "+91 (965) 564-2683",
  "address": "205 Freeman Street, Sharon, Ohio, 8248",
  "city": "Rote",
  "state": "Louisiana",
  "zip": 54365,
  "dateOfBirth": "2014-10-14",
  "class": 4,
  "section": 2
}, {
  "id": 15,
  "surName": "Carney",
  "firstName": "Terrell",
  "middleName": "Summers",
  "lastName": "Katelyn",
  "gender": "female",
  "parentName": "Drake",
  "phone": "+91 (870) 504-2100",
  "address": "504 Hicks Street, Seymour, Connecticut, 2773",
  "city": "Biddle",
  "state": "Federated States Of Micronesia",
  "zip": 54365,
  "dateOfBirth": "2014-01-07",
  "class": 4,
  "section": 3
}, {
  "id": 16,
  "surName": "Burgess",
  "firstName": "Melissa",
  "middleName": "Garrett",
  "lastName": "Quinn",
  "gender": "male",
  "parentName": "Olga",
  "phone": "+91 (875) 552-3864",
  "address": "383 Joval Court, Linganore, New York, 641",
  "city": "Takilma",
  "state": "Puerto Rico",
  "zip": 54365,
  "dateOfBirth": "2014-04-27",
  "class": 4,
  "section": 4
}, {
  "id": 17,
  "surName": "Stone",
  "firstName": "Deanna",
  "middleName": "Corrine",
  "lastName": "Pearlie",
  "gender": "female",
  "parentName": "Lilian",
  "phone": "+91 (911) 587-3359",
  "address": "978 Village Court, Lutsen, Minnesota, 3991",
  "city": "Balm",
  "state": "Florida",
  "zip": 54365,
  "dateOfBirth": "2016-01-29",
  "class": 5,
  "section": 1
}, {
  "id": 18,
  "surName": "Whitehead",
  "firstName": "Taylor",
  "middleName": "Vance",
  "lastName": "Tiffany",
  "gender": "female",
  "parentName": "Dalton",
  "phone": "+91 (970) 523-2928",
  "address": "663 Dennett Place, Brambleton, Idaho, 964",
  "city": "Sugartown",
  "state": "Kansas",
  "zip": 54365,
  "dateOfBirth": "2021-01-18",
  "class": 5,
  "section": 2
}, {
  "id": 19,
  "surName": "West",
  "firstName": "Parker",
  "middleName": "Sampson",
  "lastName": "Hallie",
  "gender": "female",
  "parentName": "Lori",
  "phone": "+91 (975) 492-2240",
  "address": "177 Sunnyside Court, Maury, Virginia, 4315",
  "city": "Adelino",
  "state": "South Carolina",
  "zip": 54365,
  "dateOfBirth": "2020-07-30",
  "class": 5,
  "section": 3
}, {
  "id": 20,
  "surName": "Floyd",
  "firstName": "Powers",
  "middleName": "Carmen",
  "lastName": "Allison",
  "gender": "male",
  "parentName": "Nina",
  "phone": "+91 (896) 560-2962",
  "address": "815 Halleck Street, Lupton, Hawaii, 8796",
  "city": "Biehle",
  "state": "Marshall Islands",
  "zip": 54365,
  "dateOfBirth": "2019-06-23",
  "class": 5,
  "section": 4
}, {
  "id": 21,
  "surName": "Bradford",
  "firstName": "Carroll",
  "middleName": "Maryellen",
  "lastName": "Alana",
  "gender": "female",
  "parentName": "Elliott",
  "phone": "+91 (882) 450-3813",
  "address": "211 Kane Street, Bentonville, Missouri, 8729",
  "city": "Rodman",
  "state": "Northern Mariana Islands",
  "zip": 54365,
  "dateOfBirth": "2016-07-27",
  "class": 6,
  "section": 1
}, {
  "id": 22,
  "surName": "Beach",
  "firstName": "Park",
  "middleName": "Morse",
  "lastName": "Winters",
  "gender": "male",
  "parentName": "Aurora",
  "phone": "+91 (940) 470-2929",
  "address": "226 Prospect Avenue, Loveland, Oregon, 5109",
  "city": "Ernstville",
  "state": "Montana",
  "zip": 54365,
  "dateOfBirth": "2020-03-20",
  "class": 6,
  "section": 2
}, {
  "id": 23,
  "surName": "Caldwell",
  "firstName": "Maura",
  "middleName": "Murphy",
  "lastName": "Eva",
  "gender": "female",
  "parentName": "Sandra",
  "phone": "+91 (822) 451-3351",
  "address": "858 Village Road, Osmond, Alabama, 7096",
  "city": "Madaket",
  "state": "North Dakota",
  "zip": 54365,
  "dateOfBirth": "2019-09-16",
  "class": 6,
  "section": 3
}, {
  "id": 24,
  "surName": "Perkins",
  "firstName": "Addie",
  "middleName": "Hess",
  "lastName": "Cobb",
  "gender": "male",
  "parentName": "Tucker",
  "phone": "+91 (926) 557-2726",
  "address": "169 Amersfort Place, Sena, Arizona, 9883",
  "city": "Wells",
  "state": "New Hampshire",
  "zip": 54365,
  "dateOfBirth": "2022-07-30",
  "class": 6,
  "section": 4
}, {
  "id": 25,
  "surName": "Fernandez",
  "firstName": "Gayle",
  "middleName": "Lane",
  "lastName": "Ida",
  "gender": "female",
  "parentName": "Kirsten",
  "phone": "+91 (822) 420-2328",
  "address": "787 Juliana Place, Rockbridge, Oklahoma, 175",
  "city": "Cannondale",
  "state": "Delaware",
  "zip": 54365,
  "dateOfBirth": "2022-08-24",
  "class": 7,
  "section": 1
}, {
  "id": 26,
  "surName": "Sullivan",
  "firstName": "Gutierrez",
  "middleName": "Mcleod",
  "lastName": "Ballard",
  "gender": "male",
  "parentName": "Irma",
  "phone": "+91 (904) 497-2924",
  "address": "833 Hope Street, Fostoria, California, 934",
  "city": "Waterford",
  "state": "Arkansas",
  "zip": 54365,
  "dateOfBirth": "2021-01-02",
  "class": 7,
  "section": 2
}, {
  "id": 27,
  "surName": "Rodgers",
  "firstName": "Francisca",
  "middleName": "Desiree",
  "lastName": "Glover",
  "gender": "male",
  "parentName": "Katina",
  "phone": "+91 (880) 542-2047",
  "address": "453 Highland Avenue, Yogaville, Colorado, 5367",
  "city": "Kilbourne",
  "state": "Pennsylvania",
  "zip": 54365,
  "dateOfBirth": "2019-10-09",
  "class": 7,
  "section": 3
}, {
  "id": 28,
  "surName": "Goff",
  "firstName": "Marina",
  "middleName": "Jeanine",
  "lastName": "Allison",
  "gender": "female",
  "parentName": "Rosalyn",
  "phone": "+91 (966) 562-2668",
  "address": "882 Fiske Place, Statenville, Palau, 4637",
  "city": "Northridge",
  "state": "South Dakota",
  "zip": 54365,
  "dateOfBirth": "2020-01-21",
  "class": 7,
  "section": 4
}, {
  "id": 29,
  "surName": "Keller",
  "firstName": "Donovan",
  "middleName": "Dunn",
  "lastName": "Hudson",
  "gender": "male",
  "parentName": "Russo",
  "phone": "+91 (928) 520-2187",
  "address": "135 Atkins Avenue, Winfred, Virgin Islands, 7737",
  "city": "Datil",
  "state": "Illinois",
  "zip": 54365,
  "dateOfBirth": "2019-03-07",
  "class": 8,
  "section": 1
}, {
  "id": 30,
  "surName": "Burnett",
  "firstName": "Reid",
  "middleName": "Parsons",
  "lastName": "Mamie",
  "gender": "female",
  "parentName": "Nola",
  "phone": "+91 (840) 529-3485",
  "address": "370 Senator Street, Nelson, American Samoa, 272",
  "city": "Allison",
  "state": "Maine",
  "zip": 54365,
  "dateOfBirth": "2022-02-23",
  "class": 8,
  "section": 2
}, {
  "id": 31,
  "surName": "Steele",
  "firstName": "Bray",
  "middleName": "Dunlap",
  "lastName": "Short",
  "gender": "male",
  "parentName": "Hogan",
  "phone": "+91 (968) 411-2016",
  "address": "399 Bleecker Street, Longbranch, New Jersey, 7951",
  "city": "Bannock",
  "state": "Nevada",
  "zip": 54365,
  "dateOfBirth": "2017-11-06",
  "class": 8,
  "section": 3
}, {
  "id": 32,
  "surName": "Moreno",
  "firstName": "Benita",
  "middleName": "Blankenship",
  "lastName": "Tamera",
  "gender": "female",
  "parentName": "Mccoy",
  "phone": "+91 (920) 529-2018",
  "address": "204 Woodside Avenue, Draper, North Carolina, 1520",
  "city": "Duryea",
  "state": "Washington",
  "zip": 54365,
  "dateOfBirth": "2018-06-23",
  "class": 8,
  "section": 4
}, {
  "id": 33,
  "surName": "Norman",
  "firstName": "Milagros",
  "middleName": "Shepard",
  "lastName": "Valeria",
  "gender": "female",
  "parentName": "Callie",
  "phone": "+91 (940) 515-3181",
  "address": "297 Kings Hwy, Carlton, Indiana, 2984",
  "city": "Crawfordsville",
  "state": "Mississippi",
  "zip": 54365,
  "dateOfBirth": "2021-11-19",
  "class": 9,
  "section": 1
}, {
  "id": 34,
  "surName": "Hamilton",
  "firstName": "Bonita",
  "middleName": "Alejandra",
  "lastName": "Burnett",
  "gender": "male",
  "parentName": "Flynn",
  "phone": "+91 (917) 494-2085",
  "address": "612 Bancroft Place, Ladera, Wisconsin, 2307",
  "city": "Dragoon",
  "state": "Texas",
  "zip": 54365,
  "dateOfBirth": "2021-01-26",
  "class": 9,
  "section": 2
}, {
  "id": 35,
  "surName": "Baker",
  "firstName": "Rosetta",
  "middleName": "Jessica",
  "lastName": "James",
  "gender": "female",
  "parentName": "Shawna",
  "phone": "+91 (923) 576-2487",
  "address": "603 Vanderveer Street, Sutton, Guam, 9473",
  "city": "Fillmore",
  "state": "Kentucky",
  "zip": 54365,
  "dateOfBirth": "2014-09-04",
  "class": 9,
  "section": 3
}, {
  "id": 36,
  "surName": "Allen",
  "firstName": "Massey",
  "middleName": "Garza",
  "lastName": "Norris",
  "gender": "male",
  "parentName": "Green",
  "phone": "+91 (999) 547-3287",
  "address": "749 Menahan Street, Savannah, Michigan, 1194",
  "city": "Coleville",
  "state": "Maryland",
  "zip": 54365,
  "dateOfBirth": "2022-04-24",
  "class": 9,
  "section": 4
}, {
  "id": 37,
  "surName": "Wolfe",
  "firstName": "Lupe",
  "middleName": "Patti",
  "lastName": "Eliza",
  "gender": "female",
  "parentName": "Abby",
  "phone": "+91 (892) 530-2616",
  "address": "693 Rockaway Parkway, Waterloo, District Of Columbia, 6240",
  "city": "Tyhee",
  "state": "Rhode Island",
  "zip": 54365,
  "dateOfBirth": "2018-07-10",
  "class": 10,
  "section": 1
}, {
  "id": 38,
  "surName": "Schroeder",
  "firstName": "Cooper",
  "middleName": "Mariana",
  "lastName": "Cotton",
  "gender": "male",
  "parentName": "Rosalie",
  "phone": "+91 (968) 465-3480",
  "address": "760 Hendrix Street, Ezel, Wyoming, 2944",
  "city": "Benson",
  "state": "Georgia",
  "zip": 54365,
  "dateOfBirth": "2019-01-21",
  "class": 10,
  "section": 2
}, {
  "id": 39,
  "surName": "Barber",
  "firstName": "Perez",
  "middleName": "Spencer",
  "lastName": "Whitley",
  "gender": "male",
  "parentName": "Serena",
  "phone": "+91 (895) 418-3368",
  "address": "970 Frost Street, Dellview, West Virginia, 1061",
  "city": "Harrison",
  "state": "Massachusetts",
  "zip": 54365,
  "dateOfBirth": "2014-08-14",
  "class": 10,
  "section": 3
}, {
  "id": 40,
  "surName": "Duran",
  "firstName": "Ross",
  "middleName": "Shannon",
  "lastName": "Fuentes",
  "gender": "male",
  "parentName": "Fernandez",
  "phone": "+91 (861) 595-2734",
  "address": "516 Calder Place, Brandermill, Vermont, 1788",
  "city": "Beaulieu",
  "state": "Nebraska",
  "zip": 54365,
  "dateOfBirth": "2016-04-09",
  "class": 10,
  "section": 4
}, {
  "id": 41,
  "surName": "Mckee",
  "firstName": "Lindsay",
  "middleName": "Soto",
  "lastName": "Rollins",
  "gender": "male",
  "parentName": "Richards",
  "phone": "+91 (834) 546-3529",
  "address": "858 Verona Street, Richmond, Tennessee, 8988",
  "city": "Frierson",
  "state": "Alaska",
  "zip": 54365,
  "dateOfBirth": "2018-09-20",
  "class": 11,
  "section": 1
}, {
  "id": 42,
  "surName": "Hurst",
  "firstName": "Montgomery",
  "middleName": "Johnston",
  "lastName": "Nichole",
  "gender": "female",
  "parentName": "Cheryl",
  "phone": "+91 (980) 426-2099",
  "address": "136 Nassau Street, Mammoth, Utah, 1235",
  "city": "Deercroft",
  "state": "New Mexico",
  "zip": 54365,
  "dateOfBirth": "2022-06-28",
  "class": 11,
  "section": 2
}, {
  "id": 43,
  "surName": "Velasquez",
  "firstName": "Marjorie",
  "middleName": "Althea",
  "lastName": "Rios",
  "gender": "male",
  "parentName": "Crane",
  "phone": "+91 (833) 463-3884",
  "address": "825 Highlawn Avenue, Martell, Ohio, 5130",
  "city": "Santel",
  "state": "Louisiana",
  "zip": 54365,
  "dateOfBirth": "2014-11-05",
  "class": 11,
  "section": 3
}, {
  "id": 44,
  "surName": "English",
  "firstName": "Michael",
  "middleName": "Palmer",
  "lastName": "Lindsey",
  "gender": "male",
  "parentName": "Rebekah",
  "phone": "+91 (817) 518-3300",
  "address": "184 Hillel Place, Nicut, Connecticut, 9101",
  "city": "Delshire",
  "state": "Federated States Of Micronesia",
  "zip": 54365,
  "dateOfBirth": "2014-08-25",
  "class": 11,
  "section": 4
}, {
  "id": 45,
  "surName": "Valencia",
  "firstName": "Petersen",
  "middleName": "Vega",
  "lastName": "Allyson",
  "gender": "female",
  "parentName": "Barlow",
  "phone": "+91 (879) 442-3689",
  "address": "987 Grafton Street, Fontanelle, New York, 1567",
  "city": "Columbus",
  "state": "Puerto Rico",
  "zip": 54365,
  "dateOfBirth": "2021-08-29",
  "class": 12,
  "section": 1
}, {
  "id": 46,
  "surName": "Carey",
  "firstName": "Buchanan",
  "middleName": "Phyllis",
  "lastName": "Lesley",
  "gender": "female",
  "parentName": "Antoinette",
  "phone": "+91 (981) 593-2035",
  "address": "140 Barwell Terrace, Bluetown, Minnesota, 819",
  "city": "Farmington",
  "state": "Florida",
  "zip": 54365,
  "dateOfBirth": "2016-11-23",
  "class": 12,
  "section": 2
}, {
  "id": 47,
  "surName": "Waters",
  "firstName": "Paul",
  "middleName": "Woodward",
  "lastName": "Traci",
  "gender": "female",
  "parentName": "Thomas",
  "phone": "+91 (977) 474-3432",
  "address": "502 Louise Terrace, Glenville, Idaho, 6272",
  "city": "Tampico",
  "state": "Kansas",
  "zip": 54365,
  "dateOfBirth": "2018-10-14",
  "class": 12,
  "section": 3
}, {
  "id": 48,
  "surName": "Vance",
  "firstName": "Vinson",
  "middleName": "Lola",
  "lastName": "Mildred",
  "gender": "female",
  "parentName": "Ericka",
  "phone": "+91 (881) 586-2571",
  "address": "785 Chestnut Avenue, Freetown, Virginia, 8755",
  "city": "Kerby",
  "state": "South Carolina",
  "zip": 54365,
  "dateOfBirth": "2016-02-24",
  "class": 12,
  "section": 4
}, {
  "id": 49,
  "surName": "Hebert",
  "firstName": "Wyatt",
  "middleName": "Bean",
  "lastName": "Celina",
  "gender": "female",
  "parentName": "Peck",
  "phone": "+91 (886) 534-2198",
  "address": "341 Beach Place, Rehrersburg, Hawaii, 4406",
  "city": "Garfield",
  "state": "Marshall Islands",
  "zip": 54365,
  "dateOfBirth": "2020-09-24",
  "class": 13,
  "section": 1
}, {
  "id": 50,
  "surName": "Langley",
  "firstName": "Sherman",
  "middleName": "Pena",
  "lastName": "Garcia",
  "gender": "male",
  "parentName": "Joy",
  "phone": "+91 (895) 481-2596",
  "address": "608 McDonald Avenue, Orason, Missouri, 1973",
  "city": "Tyro",
  "state": "Northern Mariana Islands",
  "zip": 54365,
  "dateOfBirth": "2015-05-20",
  "class": 13,
  "section": 2
}, {
  "id": 51,
  "surName": "Blankenship",
  "firstName": "Cathryn",
  "middleName": "Teresa",
  "lastName": "Lilia",
  "gender": "female",
  "parentName": "Alyssa",
  "phone": "+91 (985) 519-2187",
  "address": "880 Ridgewood Place, Frizzleburg, Oregon, 6658",
  "city": "Dixie",
  "state": "Montana",
  "zip": 54365,
  "dateOfBirth": "2016-09-04",
  "class": 13,
  "section": 3
}, {
  "id": 52,
  "surName": "Spencer",
  "firstName": "Jaclyn",
  "middleName": "Jennie",
  "lastName": "Lara",
  "gender": "male",
  "parentName": "Mara",
  "phone": "+91 (898) 517-3836",
  "address": "855 Plymouth Street, Mansfield, Alabama, 4599",
  "city": "Gorham",
  "state": "North Dakota",
  "zip": 54365,
  "dateOfBirth": "2016-09-29",
  "class": 13,
  "section": 4
}, {
  "id": 53,
  "surName": "Benson",
  "firstName": "Eloise",
  "middleName": "Navarro",
  "lastName": "Bentley",
  "gender": "male",
  "parentName": "Mccullough",
  "phone": "+91 (812) 517-2827",
  "address": "125 Mayfair Drive, Courtland, Arizona, 8997",
  "city": "Dalton",
  "state": "New Hampshire",
  "zip": 54365,
  "dateOfBirth": "2016-09-11",
  "class": 1,
  "section": 1
}, {
  "id": 54,
  "surName": "Avila",
  "firstName": "Keisha",
  "middleName": "Mathews",
  "lastName": "Neal",
  "gender": "male",
  "parentName": "Hill",
  "phone": "+91 (944) 420-2686",
  "address": "595 Hancock Street, Sanborn, Oklahoma, 4195",
  "city": "Worton",
  "state": "Delaware",
  "zip": 54365,
  "dateOfBirth": "2022-05-01",
  "class": 1,
  "section": 2
}, {
  "id": 55,
  "surName": "Welch",
  "firstName": "Pickett",
  "middleName": "Hammond",
  "lastName": "Minnie",
  "gender": "female",
  "parentName": "Ruthie",
  "phone": "+91 (856) 588-3169",
  "address": "374 Boulevard Court, Brantleyville, California, 849",
  "city": "Tonopah",
  "state": "Arkansas",
  "zip": 54365,
  "dateOfBirth": "2015-06-04",
  "class": 1,
  "section": 3
}, {
  "id": 56,
  "surName": "Franco",
  "firstName": "Ashlee",
  "middleName": "Edwards",
  "lastName": "Isabelle",
  "gender": "female",
  "parentName": "Ernestine",
  "phone": "+91 (976) 487-3100",
  "address": "269 Forbell Street, Jardine, Colorado, 7471",
  "city": "Bascom",
  "state": "Pennsylvania",
  "zip": 54365,
  "dateOfBirth": "2018-08-26",
  "class": 1,
  "section": 4
}, {
  "id": 57,
  "surName": "Potts",
  "firstName": "Dominguez",
  "middleName": "Antonia",
  "lastName": "Evans",
  "gender": "male",
  "parentName": "Mccarty",
  "phone": "+91 (869) 586-2968",
  "address": "829 Moultrie Street, Rivereno, Palau, 6220",
  "city": "Kenvil",
  "state": "South Dakota",
  "zip": 54365,
  "dateOfBirth": "2018-01-04",
  "class": 2,
  "section": 1
}, {
  "id": 58,
  "surName": "Ashley",
  "firstName": "Rena",
  "middleName": "Miller",
  "lastName": "Nanette",
  "gender": "female",
  "parentName": "Mollie",
  "phone": "+91 (900) 455-3342",
  "address": "869 Wyckoff Street, Cochranville, Virgin Islands, 9526",
  "city": "Nord",
  "state": "Illinois",
  "zip": 54365,
  "dateOfBirth": "2016-07-31",
  "class": 2,
  "section": 2
}, {
  "id": 59,
  "surName": "Knowles",
  "firstName": "Houston",
  "middleName": "Marcie",
  "lastName": "Winnie",
  "gender": "female",
  "parentName": "Hendricks",
  "phone": "+91 (907) 529-3205",
  "address": "441 Applegate Court, Cataract, American Samoa, 736",
  "city": "Volta",
  "state": "Maine",
  "zip": 54365,
  "dateOfBirth": "2020-06-17",
  "class": 2,
  "section": 3
}, {
  "id": 60,
  "surName": "Hanson",
  "firstName": "Terry",
  "middleName": "Woodard",
  "lastName": "Arnold",
  "gender": "male",
  "parentName": "Lewis",
  "phone": "+91 (872) 597-3540",
  "address": "899 Navy Street, Clarksburg, New Jersey, 8213",
  "city": "Hachita",
  "state": "Nevada",
  "zip": 54365,
  "dateOfBirth": "2021-04-20",
  "class": 2,
  "section": 4
}, {
  "id": 61,
  "surName": "Maxwell",
  "firstName": "Debbie",
  "middleName": "Douglas",
  "lastName": "West",
  "gender": "male",
  "parentName": "Clayton",
  "phone": "+91 (863) 454-2894",
  "address": "329 Harkness Avenue, Chesterfield, North Carolina, 4007",
  "city": "Chical",
  "state": "Washington",
  "zip": 54365,
  "dateOfBirth": "2022-10-19",
  "class": 3,
  "section": 1
}, {
  "id": 62,
  "surName": "Jennings",
  "firstName": "Patricia",
  "middleName": "May",
  "lastName": "Reyes",
  "gender": "male",
  "parentName": "Nielsen",
  "phone": "+91 (918) 517-3854",
  "address": "227 Channel Avenue, Westmoreland, Indiana, 6798",
  "city": "Allamuchy",
  "state": "Mississippi",
  "zip": 54365,
  "dateOfBirth": "2018-09-06",
  "class": 3,
  "section": 2
}, {
  "id": 63,
  "surName": "Winters",
  "firstName": "Jamie",
  "middleName": "Lorna",
  "lastName": "Twila",
  "gender": "female",
  "parentName": "Aguirre",
  "phone": "+91 (851) 489-2996",
  "address": "305 Ditmas Avenue, Dorneyville, Wisconsin, 6200",
  "city": "Glenshaw",
  "state": "Texas",
  "zip": 54365,
  "dateOfBirth": "2018-09-16",
  "class": 3,
  "section": 3
}, {
  "id": 64,
  "surName": "Shepherd",
  "firstName": "Gabriela",
  "middleName": "Freida",
  "lastName": "Walton",
  "gender": "male",
  "parentName": "Contreras",
  "phone": "+91 (879) 443-3552",
  "address": "350 Furman Street, Grantville, Guam, 362",
  "city": "Whitehaven",
  "state": "Kentucky",
  "zip": 54365,
  "dateOfBirth": "2014-12-19",
  "class": 3,
  "section": 4
}, {
  "id": 65,
  "surName": "Greene",
  "firstName": "Sharlene",
  "middleName": "Goodman",
  "lastName": "Jerry",
  "gender": "female",
  "parentName": "Ronda",
  "phone": "+91 (879) 576-2144",
  "address": "706 Billings Place, Brutus, Michigan, 5197",
  "city": "Spelter",
  "state": "Maryland",
  "zip": 54365,
  "dateOfBirth": "2015-01-27",
  "class": 4,
  "section": 1
}, {
  "id": 66,
  "surName": "Underwood",
  "firstName": "Monica",
  "middleName": "Bryant",
  "lastName": "Wendi",
  "gender": "female",
  "parentName": "Grant",
  "phone": "+91 (808) 494-3745",
  "address": "554 Dare Court, Lund, District Of Columbia, 8738",
  "city": "Jessie",
  "state": "Rhode Island",
  "zip": 54365,
  "dateOfBirth": "2019-10-26",
  "class": 4,
  "section": 2
}, {
  "id": 67,
  "surName": "Malone",
  "firstName": "Lillian",
  "middleName": "Stephenson",
  "lastName": "Carla",
  "gender": "female",
  "parentName": "Kara",
  "phone": "+91 (846) 459-2814",
  "address": "218 Schenck Place, Wawona, Wyoming, 2887",
  "city": "Zortman",
  "state": "Georgia",
  "zip": 54365,
  "dateOfBirth": "2014-01-26",
  "class": 4,
  "section": 3
}, {
  "id": 68,
  "surName": "Barnes",
  "firstName": "Cooke",
  "middleName": "Boyle",
  "lastName": "Caitlin",
  "gender": "female",
  "parentName": "Ayers",
  "phone": "+91 (852) 426-2588",
  "address": "209 Clove Road, Grapeview, West Virginia, 102",
  "city": "Broadlands",
  "state": "Massachusetts",
  "zip": 54365,
  "dateOfBirth": "2022-01-24",
  "class": 4,
  "section": 4
}, {
  "id": 69,
  "surName": "Duffy",
  "firstName": "Snider",
  "middleName": "Lessie",
  "lastName": "Adriana",
  "gender": "female",
  "parentName": "Butler",
  "phone": "+91 (945) 545-2472",
  "address": "555 Reeve Place, Trail, Vermont, 2880",
  "city": "Williamson",
  "state": "Nebraska",
  "zip": 54365,
  "dateOfBirth": "2015-07-10",
  "class": 5,
  "section": 1
}, {
  "id": 70,
  "surName": "Roth",
  "firstName": "Cathleen",
  "middleName": "Watts",
  "lastName": "Bowen",
  "gender": "male",
  "parentName": "Hays",
  "phone": "+91 (897) 511-2054",
  "address": "381 Clark Street, Summerset, Tennessee, 8669",
  "city": "Starks",
  "state": "Alaska",
  "zip": 54365,
  "dateOfBirth": "2021-05-27",
  "class": 5,
  "section": 2
}, {
  "id": 71,
  "surName": "Albert",
  "firstName": "Mathis",
  "middleName": "Christian",
  "lastName": "Daniels",
  "gender": "male",
  "parentName": "Cochran",
  "phone": "+91 (852) 426-2052",
  "address": "760 Conklin Avenue, Austinburg, Utah, 3636",
  "city": "Clinton",
  "state": "New Mexico",
  "zip": 54365,
  "dateOfBirth": "2019-06-06",
  "class": 5,
  "section": 3
}, {
  "id": 72,
  "surName": "Wiley",
  "firstName": "Charles",
  "middleName": "Gena",
  "lastName": "Trisha",
  "gender": "female",
  "parentName": "Davidson",
  "phone": "+91 (941) 572-2186",
  "address": "850 Vernon Avenue, Smock, Ohio, 7967",
  "city": "Elliston",
  "state": "Louisiana",
  "zip": 54365,
  "dateOfBirth": "2016-06-22",
  "class": 5,
  "section": 4
}, {
  "id": 73,
  "surName": "Harvey",
  "firstName": "Rosella",
  "middleName": "Bass",
  "lastName": "Brennan",
  "gender": "male",
  "parentName": "Meghan",
  "phone": "+91 (922) 517-2472",
  "address": "731 Autumn Avenue, Toftrees, Connecticut, 4102",
  "city": "Camptown",
  "state": "Federated States Of Micronesia",
  "zip": 54365,
  "dateOfBirth": "2016-09-06",
  "class": 6,
  "section": 1
}, {
  "id": 74,
  "surName": "Christian",
  "firstName": "Kerry",
  "middleName": "Lesa",
  "lastName": "Eve",
  "gender": "female",
  "parentName": "Mccormick",
  "phone": "+91 (876) 452-2335",
  "address": "647 Gatling Place, Woodburn, New York, 8163",
  "city": "Machias",
  "state": "Puerto Rico",
  "zip": 54365,
  "dateOfBirth": "2022-05-27",
  "class": 6,
  "section": 2
}, {
  "id": 75,
  "surName": "Marquez",
  "firstName": "Hawkins",
  "middleName": "Washington",
  "lastName": "Alisha",
  "gender": "female",
  "parentName": "Susanna",
  "phone": "+91 (841) 549-3004",
  "address": "352 Surf Avenue, Hasty, Minnesota, 1945",
  "city": "Newcastle",
  "state": "Florida",
  "zip": 54365,
  "dateOfBirth": "2020-03-30",
  "class": 6,
  "section": 3
}, {
  "id": 76,
  "surName": "Sellers",
  "firstName": "Benton",
  "middleName": "Mason",
  "lastName": "Davis",
  "gender": "male",
  "parentName": "Cherie",
  "phone": "+91 (896) 597-3514",
  "address": "662 Cherry Street, Cleary, Idaho, 8404",
  "city": "Ventress",
  "state": "Kansas",
  "zip": 54365,
  "dateOfBirth": "2018-07-19",
  "class": 6,
  "section": 4
}, {
  "id": 77,
  "surName": "Anderson",
  "firstName": "Glenn",
  "middleName": "Atkins",
  "lastName": "Bethany",
  "gender": "female",
  "parentName": "Dorothea",
  "phone": "+91 (938) 525-2010",
  "address": "425 Perry Terrace, Idamay, Virginia, 1976",
  "city": "Harleigh",
  "state": "South Carolina",
  "zip": 54365,
  "dateOfBirth": "2018-06-18",
  "class": 7,
  "section": 1
}, {
  "id": 78,
  "surName": "Hughes",
  "firstName": "Elvira",
  "middleName": "Annette",
  "lastName": "Mcpherson",
  "gender": "male",
  "parentName": "Pate",
  "phone": "+91 (881) 585-3075",
  "address": "849 Bevy Court, Carrizo, Hawaii, 1327",
  "city": "Convent",
  "state": "Marshall Islands",
  "zip": 54365,
  "dateOfBirth": "2022-12-05",
  "class": 7,
  "section": 2
}, {
  "id": 79,
  "surName": "Mclean",
  "firstName": "Cash",
  "middleName": "Richmond",
  "lastName": "Boyer",
  "gender": "male",
  "parentName": "Mercedes",
  "phone": "+91 (945) 491-2541",
  "address": "805 Metrotech Courtr, Dahlen, Missouri, 476",
  "city": "Westboro",
  "state": "Northern Mariana Islands",
  "zip": 54365,
  "dateOfBirth": "2017-05-18",
  "class": 7,
  "section": 3
}, {
  "id": 80,
  "surName": "Hull",
  "firstName": "Leanna",
  "middleName": "June",
  "lastName": "Cervantes",
  "gender": "male",
  "parentName": "Phoebe",
  "phone": "+91 (891) 461-3944",
  "address": "493 Johnson Street, Sabillasville, Oregon, 4175",
  "city": "Wheaton",
  "state": "Montana",
  "zip": 54365,
  "dateOfBirth": "2022-09-25",
  "class": 7,
  "section": 4
}, {
  "id": 81,
  "surName": "Hoffman",
  "firstName": "Stewart",
  "middleName": "Darlene",
  "lastName": "Juanita",
  "gender": "female",
  "parentName": "Whitaker",
  "phone": "+91 (901) 409-2446",
  "address": "863 Locust Avenue, Ada, Alabama, 8838",
  "city": "Ilchester",
  "state": "North Dakota",
  "zip": 54365,
  "dateOfBirth": "2020-01-17",
  "class": 8,
  "section": 1
}, {
  "id": 82,
  "surName": "Brooks",
  "firstName": "Josie",
  "middleName": "Pam",
  "lastName": "Elsa",
  "gender": "female",
  "parentName": "Claudette",
  "phone": "+91 (943) 549-2500",
  "address": "105 Kermit Place, Wikieup, Arizona, 1330",
  "city": "Frank",
  "state": "New Hampshire",
  "zip": 54365,
  "dateOfBirth": "2016-06-02",
  "class": 8,
  "section": 2
}, {
  "id": 83,
  "surName": "Blanchard",
  "firstName": "Shelia",
  "middleName": "Donaldson",
  "lastName": "Wilkins",
  "gender": "male",
  "parentName": "Theresa",
  "phone": "+91 (819) 517-2787",
  "address": "974 Branton Street, Barclay, Oklahoma, 3072",
  "city": "Homeworth",
  "state": "Delaware",
  "zip": 54365,
  "dateOfBirth": "2019-11-26",
  "class": 8,
  "section": 3
}, {
  "id": 84,
  "surName": "Lopez",
  "firstName": "Jayne",
  "middleName": "Jeanie",
  "lastName": "Chris",
  "gender": "female",
  "parentName": "Suarez",
  "phone": "+91 (927) 577-2904",
  "address": "668 Independence Avenue, Edenburg, California, 2406",
  "city": "Cazadero",
  "state": "Arkansas",
  "zip": 54365,
  "dateOfBirth": "2020-01-14",
  "class": 8,
  "section": 4
}, {
  "id": 85,
  "surName": "Nieves",
  "firstName": "Ginger",
  "middleName": "Foley",
  "lastName": "Rachael",
  "gender": "female",
  "parentName": "Gomez",
  "phone": "+91 (915) 461-3520",
  "address": "957 Irving Place, Sparkill, Colorado, 3287",
  "city": "Wright",
  "state": "Pennsylvania",
  "zip": 54365,
  "dateOfBirth": "2017-10-26",
  "class": 9,
  "section": 1
}, {
  "id": 86,
  "surName": "Parker",
  "firstName": "Melendez",
  "middleName": "Stuart",
  "lastName": "Joan",
  "gender": "female",
  "parentName": "Latoya",
  "phone": "+91 (990) 529-2455",
  "address": "109 Norman Avenue, Tivoli, Palau, 4817",
  "city": "Coultervillle",
  "state": "South Dakota",
  "zip": 54365,
  "dateOfBirth": "2017-08-16",
  "class": 9,
  "section": 2
}, {
  "id": 87,
  "surName": "Martinez",
  "firstName": "Earnestine",
  "middleName": "Benjamin",
  "lastName": "Berg",
  "gender": "male",
  "parentName": "Mary",
  "phone": "+91 (985) 404-2323",
  "address": "261 Bennet Court, Chemung, Virgin Islands, 5987",
  "city": "Robinette",
  "state": "Illinois",
  "zip": 54365,
  "dateOfBirth": "2017-08-27",
  "class": 9,
  "section": 3
}, {
  "id": 88,
  "surName": "Case",
  "firstName": "Marietta",
  "middleName": "Grimes",
  "lastName": "Jodi",
  "gender": "female",
  "parentName": "Buck",
  "phone": "+91 (832) 584-3881",
  "address": "349 Madison Street, Cumberland, American Samoa, 7600",
  "city": "Whitewater",
  "state": "Maine",
  "zip": 54365,
  "dateOfBirth": "2020-12-07",
  "class": 9,
  "section": 4
}, {
  "id": 89,
  "surName": "Durham",
  "firstName": "Kay",
  "middleName": "Ramona",
  "lastName": "Elise",
  "gender": "female",
  "parentName": "Gould",
  "phone": "+91 (990) 414-3464",
  "address": "244 Greenwood Avenue, Crown, New Jersey, 8693",
  "city": "Ahwahnee",
  "state": "Nevada",
  "zip": 54365,
  "dateOfBirth": "2020-10-14",
  "class": 10,
  "section": 1
}, {
  "id": 90,
  "surName": "Wiggins",
  "firstName": "Debra",
  "middleName": "Concepcion",
  "lastName": "Etta",
  "gender": "female",
  "parentName": "Floyd",
  "phone": "+91 (853) 536-2247",
  "address": "118 Herkimer Court, Bartley, North Carolina, 730",
  "city": "Coloma",
  "state": "Washington",
  "zip": 54365,
  "dateOfBirth": "2016-03-27",
  "class": 10,
  "section": 2
}, {
  "id": 91,
  "surName": "Shelton",
  "firstName": "Schroeder",
  "middleName": "Cruz",
  "lastName": "Medina",
  "gender": "male",
  "parentName": "Andrea",
  "phone": "+91 (941) 430-2575",
  "address": "828 Monroe Place, Southmont, Indiana, 5270",
  "city": "Thynedale",
  "state": "Mississippi",
  "zip": 54365,
  "dateOfBirth": "2018-12-04",
  "class": 10,
  "section": 3
}, {
  "id": 92,
  "surName": "Mills",
  "firstName": "Shelley",
  "middleName": "Powell",
  "lastName": "Owen",
  "gender": "male",
  "parentName": "Christina",
  "phone": "+91 (804) 438-3084",
  "address": "548 Roder Avenue, Celeryville, Wisconsin, 7223",
  "city": "Chestnut",
  "state": "Texas",
  "zip": 54365,
  "dateOfBirth": "2021-12-16",
  "class": 10,
  "section": 4
}, {
  "id": 93,
  "surName": "Crawford",
  "firstName": "Beck",
  "middleName": "Reed",
  "lastName": "Shana",
  "gender": "female",
  "parentName": "Lester",
  "phone": "+91 (893) 417-2622",
  "address": "672 Duryea Court, Bison, Guam, 1859",
  "city": "Riceville",
  "state": "Kentucky",
  "zip": 54365,
  "dateOfBirth": "2021-12-21",
  "class": 11,
  "section": 1
}, {
  "id": 94,
  "surName": "Reeves",
  "firstName": "Juliette",
  "middleName": "Pennington",
  "lastName": "Hahn",
  "gender": "male",
  "parentName": "Bullock",
  "phone": "+91 (909) 567-2005",
  "address": "687 Woods Place, Elizaville, Michigan, 1339",
  "city": "Foscoe",
  "state": "Maryland",
  "zip": 54365,
  "dateOfBirth": "2016-01-23",
  "class": 11,
  "section": 2
}, {
  "id": 95,
  "surName": "Gillespie",
  "firstName": "Ayala",
  "middleName": "Foster",
  "lastName": "Shanna",
  "gender": "female",
  "parentName": "Bertie",
  "phone": "+91 (845) 570-2857",
  "address": "476 Douglass Street, Kieler, District Of Columbia, 758",
  "city": "Lemoyne",
  "state": "Rhode Island",
  "zip": 54365,
  "dateOfBirth": "2015-02-19",
  "class": 11,
  "section": 3
}, {
  "id": 96,
  "surName": "Cox",
  "firstName": "Strong",
  "middleName": "Mccarthy",
  "lastName": "Kristina",
  "gender": "female",
  "parentName": "Colleen",
  "phone": "+91 (810) 465-2954",
  "address": "112 Hanson Place, Darlington, Wyoming, 1159",
  "city": "Woodlake",
  "state": "Georgia",
  "zip": 54365,
  "dateOfBirth": "2014-07-03",
  "class": 11,
  "section": 4
}, {
  "id": 97,
  "surName": "Wynn",
  "firstName": "Cortez",
  "middleName": "Tamika",
  "lastName": "Holt",
  "gender": "male",
  "parentName": "Annabelle",
  "phone": "+91 (818) 550-3565",
  "address": "266 Central Avenue, Catharine, West Virginia, 4494",
  "city": "Westwood",
  "state": "Massachusetts",
  "zip": 54365,
  "dateOfBirth": "2021-03-08",
  "class": 12,
  "section": 1
}, {
  "id": 98,
  "surName": "Gutierrez",
  "firstName": "Roseann",
  "middleName": "Elisabeth",
  "lastName": "Delaney",
  "gender": "male",
  "parentName": "Sharron",
  "phone": "+91 (871) 510-3742",
  "address": "638 Brooklyn Road, Freeburn, Vermont, 2070",
  "city": "Emory",
  "state": "Nebraska",
  "zip": 54365,
  "dateOfBirth": "2019-06-20",
  "class": 12,
  "section": 2
}, {
  "id": 99,
  "surName": "Workman",
  "firstName": "Jenifer",
  "middleName": "Hannah",
  "lastName": "Marianne",
  "gender": "female",
  "parentName": "Benson",
  "phone": "+91 (977) 446-3457",
  "address": "210 Amherst Street, Fairacres, Tennessee, 5355",
  "city": "Lloyd",
  "state": "Alaska",
  "zip": 54365,
  "dateOfBirth": "2016-02-14",
  "class": 12,
  "section": 3
}, {
  "id": 100,
  "surName": "Santos",
  "firstName": "Chaney",
  "middleName": "Snyder",
  "lastName": "Chandra",
  "gender": "female",
  "parentName": "Misty",
  "phone": "+91 (841) 443-2428",
  "address": "541 Lacon Court, Cartwright, Utah, 4899",
  "city": "Allentown",
  "state": "New Mexico",
  "zip": 54365,
  "dateOfBirth": "2016-06-12",
  "class": 12,
  "section": 4
}, {
  "id": 101,
  "surName": "Lynn",
  "firstName": "Natalia",
  "middleName": "Howell",
  "lastName": "Curtis",
  "gender": "male",
  "parentName": "Jenna",
  "phone": "+91 (963) 443-3828",
  "address": "150 Bassett Avenue, Breinigsville, Ohio, 1048",
  "city": "Utting",
  "state": "Louisiana",
  "zip": 54365,
  "dateOfBirth": "2022-06-22",
  "class": 13,
  "section": 1
}, {
  "id": 102,
  "surName": "York",
  "firstName": "Ruby",
  "middleName": "Maritza",
  "lastName": "Kelley",
  "gender": "female",
  "parentName": "Randolph",
  "phone": "+91 (915) 509-3043",
  "address": "907 Hinckley Place, Montura, Connecticut, 3706",
  "city": "Mayfair",
  "state": "Federated States Of Micronesia",
  "zip": 54365,
  "dateOfBirth": "2018-07-07",
  "class": 13,
  "section": 2
}, {
  "id": 103,
  "surName": "Schmidt",
  "firstName": "Banks",
  "middleName": "Byers",
  "lastName": "Nita",
  "gender": "female",
  "parentName": "Wong",
  "phone": "+91 (998) 589-2100",
  "address": "896 Euclid Avenue, Swartzville, New York, 4774",
  "city": "Zarephath",
  "state": "Puerto Rico",
  "zip": 54365,
  "dateOfBirth": "2015-10-04",
  "class": 13,
  "section": 3
}, {
  "id": 104,
  "surName": "Rice",
  "firstName": "Acevedo",
  "middleName": "Sophia",
  "lastName": "Jacqueline",
  "gender": "female",
  "parentName": "Scott",
  "phone": "+91 (996) 499-2002",
  "address": "401 Hegeman Avenue, Wilsonia, Minnesota, 8862",
  "city": "Hiwasse",
  "state": "Florida",
  "zip": 54365,
  "dateOfBirth": "2019-10-20",
  "class": 13,
  "section": 4
}, {
  "id": 105,
  "surName": "Schneider",
  "firstName": "Baxter",
  "middleName": "Nicholson",
  "lastName": "Roach",
  "gender": "male",
  "parentName": "Marguerite",
  "phone": "+91 (854) 579-3711",
  "address": "452 Richards Street, Emison, Idaho, 7664",
  "city": "Blairstown",
  "state": "Kansas",
  "zip": 54365,
  "dateOfBirth": "2018-10-28",
  "class": 1,
  "section": 1
}, {
  "id": 106,
  "surName": "Sherman",
  "firstName": "Workman",
  "middleName": "Hobbs",
  "lastName": "Garner",
  "gender": "male",
  "parentName": "Alyce",
  "phone": "+91 (938) 544-2096",
  "address": "668 Lincoln Terrace, Yukon, Virginia, 4539",
  "city": "Ryderwood",
  "state": "South Carolina",
  "zip": 54365,
  "dateOfBirth": "2020-01-18",
  "class": 1,
  "section": 2
}, {
  "id": 107,
  "surName": "Levine",
  "firstName": "Clarke",
  "middleName": "Montoya",
  "lastName": "Sparks",
  "gender": "male",
  "parentName": "Frances",
  "phone": "+91 (926) 551-2650",
  "address": "192 Karweg Place, Talpa, Hawaii, 3199",
  "city": "Mappsville",
  "state": "Marshall Islands",
  "zip": 54365,
  "dateOfBirth": "2020-06-22",
  "class": 1,
  "section": 3
}, {
  "id": 108,
  "surName": "Cantrell",
  "firstName": "Fay",
  "middleName": "Karin",
  "lastName": "Katheryn",
  "gender": "female",
  "parentName": "Adele",
  "phone": "+91 (888) 574-3045",
  "address": "152 Franklin Avenue, Roberts, Missouri, 8563",
  "city": "Elliott",
  "state": "Northern Mariana Islands",
  "zip": 54365,
  "dateOfBirth": "2022-09-13",
  "class": 1,
  "section": 4
}, {
  "id": 109,
  "surName": "Lee",
  "firstName": "Sutton",
  "middleName": "Patrica",
  "lastName": "Dillard",
  "gender": "male",
  "parentName": "Estes",
  "phone": "+91 (997) 434-3112",
  "address": "111 Bragg Court, Coyote, Oregon, 8885",
  "city": "Steinhatchee",
  "state": "Montana",
  "zip": 54365,
  "dateOfBirth": "2017-06-17",
  "class": 2,
  "section": 1
}, {
  "id": 110,
  "surName": "Obrien",
  "firstName": "Burgess",
  "middleName": "Nettie",
  "lastName": "Brandi",
  "gender": "female",
  "parentName": "Michelle",
  "phone": "+91 (970) 442-3375",
  "address": "731 Rost Place, Springhill, Alabama, 5492",
  "city": "Fairview",
  "state": "North Dakota",
  "zip": 54365,
  "dateOfBirth": "2019-08-27",
  "class": 2,
  "section": 2
}, {
  "id": 111,
  "surName": "Harper",
  "firstName": "Shari",
  "middleName": "Sylvia",
  "lastName": "Belinda",
  "gender": "female",
  "parentName": "Velazquez",
  "phone": "+91 (971) 515-2597",
  "address": "972 Woodpoint Road, Sussex, Arizona, 664",
  "city": "Westphalia",
  "state": "New Hampshire",
  "zip": 54365,
  "dateOfBirth": "2019-02-04",
  "class": 2,
  "section": 3
}, {
  "id": 112,
  "surName": "Reynolds",
  "firstName": "Daisy",
  "middleName": "Doris",
  "lastName": "Kemp",
  "gender": "male",
  "parentName": "English",
  "phone": "+91 (927) 525-3970",
  "address": "822 Canarsie Road, Oretta, Oklahoma, 2410",
  "city": "Brule",
  "state": "Delaware",
  "zip": 54365,
  "dateOfBirth": "2020-07-29",
  "class": 2,
  "section": 4
}, {
  "id": 113,
  "surName": "Hopper",
  "firstName": "Kitty",
  "middleName": "Susan",
  "lastName": "Schneider",
  "gender": "male",
  "parentName": "Marcy",
  "phone": "+91 (893) 524-2423",
  "address": "588 Vandam Street, Freelandville, California, 5894",
  "city": "Gila",
  "state": "Arkansas",
  "zip": 54365,
  "dateOfBirth": "2018-10-22",
  "class": 3,
  "section": 1
}, {
  "id": 114,
  "surName": "Salas",
  "firstName": "Puckett",
  "middleName": "Franks",
  "lastName": "Eleanor",
  "gender": "female",
  "parentName": "Celia",
  "phone": "+91 (920) 400-3146",
  "address": "368 Turnbull Avenue, Kimmell, Colorado, 3547",
  "city": "Munjor",
  "state": "Pennsylvania",
  "zip": 54365,
  "dateOfBirth": "2015-01-07",
  "class": 3,
  "section": 2
}, {
  "id": 115,
  "surName": "Ortega",
  "firstName": "Linda",
  "middleName": "Leah",
  "lastName": "Maricela",
  "gender": "female",
  "parentName": "Nancy",
  "phone": "+91 (943) 596-2139",
  "address": "948 Quentin Street, Cawood, Palau, 6879",
  "city": "Shrewsbury",
  "state": "South Dakota",
  "zip": 54365,
  "dateOfBirth": "2015-09-20",
  "class": 3,
  "section": 3
}, {
  "id": 116,
  "surName": "Adams",
  "firstName": "Becker",
  "middleName": "Glenna",
  "lastName": "Cornelia",
  "gender": "female",
  "parentName": "Flossie",
  "phone": "+91 (855) 441-3134",
  "address": "103 Manor Court, Eggertsville, Virgin Islands, 5110",
  "city": "Hanover",
  "state": "Illinois",
  "zip": 54365,
  "dateOfBirth": "2019-07-26",
  "class": 3,
  "section": 4
}, {
  "id": 117,
  "surName": "Byrd",
  "firstName": "Sanders",
  "middleName": "Freda",
  "lastName": "Slater",
  "gender": "male",
  "parentName": "Gordon",
  "phone": "+91 (835) 540-3618",
  "address": "627 Keen Court, Warren, American Samoa, 2861",
  "city": "Groveville",
  "state": "Maine",
  "zip": 54365,
  "dateOfBirth": "2017-05-19",
  "class": 4,
  "section": 1
}, {
  "id": 118,
  "surName": "Lucas",
  "firstName": "Alma",
  "middleName": "Mann",
  "lastName": "Augusta",
  "gender": "female",
  "parentName": "Peggy",
  "phone": "+91 (872) 416-2965",
  "address": "579 Christopher Avenue, Itmann, New Jersey, 5343",
  "city": "Bangor",
  "state": "Nevada",
  "zip": 54365,
  "dateOfBirth": "2014-10-02",
  "class": 4,
  "section": 2
}, {
  "id": 119,
  "surName": "Strong",
  "firstName": "Duffy",
  "middleName": "Leola",
  "lastName": "Patsy",
  "gender": "female",
  "parentName": "Fields",
  "phone": "+91 (944) 400-3710",
  "address": "645 Emmons Avenue, Echo, North Carolina, 3594",
  "city": "Worcester",
  "state": "Washington",
  "zip": 54365,
  "dateOfBirth": "2014-10-08",
  "class": 4,
  "section": 3
}, {
  "id": 120,
  "surName": "Rose",
  "firstName": "Goodwin",
  "middleName": "Dona",
  "lastName": "Vargas",
  "gender": "male",
  "parentName": "Clemons",
  "phone": "+91 (943) 458-2915",
  "address": "229 Empire Boulevard, Inkerman, Indiana, 6630",
  "city": "Waiohinu",
  "state": "Mississippi",
  "zip": 54365,
  "dateOfBirth": "2014-07-10",
  "class": 4,
  "section": 4
}]
  

@Injectable({
    providedIn: "root"
})
export class StudentsService {
    
    getStudents(){
      return of(STUDENTS);
    }

    validateNewStudents(){

    }

    getStudentById(id: string){
      const idNum = Number(id);
      return of(STUDENTS.find((s: any) => s.id === idNum));
    }
  }